---
title: "Annotation of Frozen BMMCs (Healthy Control 1) 10x dataset"
output: html_document
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

```{r global_options, include=FALSE}
library(ggplot2)
library(dplyr)
library(dropestr)
# library(dropEstAnalysis)
# library(parallel)
# library(reshape2)
# library(RColorBrewer)

theme_set(theme_base)

set.seed(42)
kDataPath <- '/d0-mendel/home/viktor_petukhov/Data/10x/frozen_bmmc_healthy_donor1/'
kEstFolder <- paste0(kDataPath, 'est_11_10_umi_quality/')
k10xFolder <- paste0(kDataPath, 'filtered_matrices_mex/hg19/')

PlotClustering <- function(pgd, clusters) {
  PlotPagodaEmbeding(pgd, clusters, show.ticks=F, size=1, alpha=0.5, nudge_x=1, nudge_y=1, font.size=NULL) +
    ggplot2::scale_size_continuous(range=c(3, 6))
}

AnnotateClusters <- function(clusters, type.clusters) {
  clusters.annotated <- as.integer(clusters) %>% setNames(names(clusters))
  for (n in names(type.clusters)) {
    clusters.annotated[clusters.annotated %in% type.clusters[[n]]] <- n
  }
  
  return(clusters.annotated)
}

PlotExpressionHeatmap <- function(matrix, clusters, genes) {
  pheatmap::pheatmap(t(matrix[rownames(clusters), genes]), annotation_col=clusters, 
                     cluster_rows=F, cluster_cols=F, show_colnames=F)
}
```

```{r}
holder <- readRDS(paste0(kEstFolder, 'bmmc_no_umi.rds'))
genes <- read.table(paste0(k10xFolder, 'genes.tsv')) %>% filter(V2 %in% names(which(table(V2) == 1)))
gene_id_to_names <- setNames(genes$V2, genes$V1)
holder$cm <- holder$cm[grep("^[^;]+$", rownames(holder$cm)),]
holder$cm_raw <- holder$cm_raw[grep("^[^;]+$", rownames(holder$cm_raw)),]
```

```{r}
umis_per_cell <- sort(Matrix::colSums(holder$cm_raw), decreasing=T)
est_cell_num <- EstimateCellsNumber(umis_per_cell)
```

Quality scores:  
```{r, message=FALSE}
scores <- ScorePipelineCells(holder, mit.chromosome.name='MT', predict.all=T, verbose=T)[names(umis_per_cell)]
PlotCellScores(scores, cells.number=est_cell_num)
```

Pagoda run:  
```{r, message=FALSE}
real_cbs <- names(scores)[1:est_cell_num$expected]
real_cbs <- real_cbs[scores[real_cbs] > 0.9]

r_cm <- holder$cm_raw[, real_cbs]
r_cm <- r_cm[intersect(rownames(r_cm), names(gene_id_to_names)), ]
rownames(r_cm) <- gene_id_to_names[rownames(r_cm)]

pgd <- GetPagoda(r_cm, n.cores=30)

clusters <- pgd$clusters$PCA$infomap
log_mtx <- log10(1e-3 + as.matrix(pgd$counts[names(clusters), ]))
```

Initial clustering:  
```{r}
PlotPagodaEmbeding(pgd, clustering.type='infomap')
```

## Initial labeling
Description: 
- https://www.bdbiosciences.com/documents/Bcell_Brochure.pdf - B cells
- https://www.bdbiosciences.com/documents/cd_marker_handbook.pdf - CD Markers

```{r}
de_genes <- pgd$getDifferentialGenes(type='PCA', clusterType='infomap', upregulated.only=T) %>%
  lapply(rownames)

major_cell_types <- lst(
  `T cells` = sapply(de_genes, function(genes) 'CD3D' %in% genes) %>% which() %>% names() %>% as.integer(),
  `B cells` = sapply(de_genes, function(genes) 'MS4A1' %in% genes) %>% which() %>% names() %>% as.integer()
)

if (length(major_cell_types %>% unlist()) != length(major_cell_types %>% unlist() %>% unique())) stop("Something goes wrong")
```

```{r}
heatmap_genes <- c(
  'CD19', 'MME', 'MS4A1',
  'CD3D',
  'LYZ', 'CD14',
  'GZMA', 'GZMB', 'GNLY', 'NKG7',
  'FCER1A', 'CST3',
  'CD34', 'PTPRC', 'ITGB1', 'ENG',
  'EPCAM', 'APOE',
  'GYPA', 'CD36'
  )

heatmap_clusters <- data.frame(Cluster=sort(clusters))
heatmap_clusters <- heatmap_clusters[!(as.integer(heatmap_clusters$Cluster) %in% unlist(major_cell_types)), ,drop=FALSE]
# heatmap_clusters <- heatmap_clusters[as.integer(heatmap_clusters$Cluster) > 14, ,drop=FALSE]
PlotExpressionHeatmap(log_mtx, heatmap_clusters, heatmap_genes)
```

```{r}
type_ids <- c(major_cell_types, lst(
  `CD14+ Monocytes` = c(2),
  `NK cells` = c(5),
  `Dendritic cells` = c(13),
  `Mesenchymal stroma cells` = c(9, 15),
  `Epithelial cells` = 10,
  `Erythrocytes` = c(4, 6, 8, 9)
))

type_ids$`B cells` <- c(type_ids$`B cells`, 11, 12, 14, 18)
type_ids$`T cells` <- c(type_ids$`T cells`, 16, 17)

markers_df <- data.frame(
  Type = c("B cells", "T cells", "CD14+ Monocytes", "NK cells", "Dendritic cells", "Mesenchymal stroma cells", 
           "Epithelial cells", "Erythrocytes"),
  Markers = c("CD19, MME (CD10), MS4A1 (CD20)", "CD3D", "LYZ, CD14", "GZMA, GZMB, GNLY, NKG7", "FCER1A, CST3", 
              "CD34, PTPRC (CD45), ITGB1 (CD29), ENG(CD105)", "EPCAM (CD326), CD226-, APOE (CD165)", "GYPA (CD235a), CD36")
)

markers_df$Clusters <- sapply(type_ids, paste, collapse=", ")[as.character(markers_df$Type)]
markers_df
```

```{r, message=FALSE, warning=FALSE}
clusters_annotated <- AnnotateClusters(clusters, type_ids)
PlotClustering(pgd, clusters_annotated)
```

## B cells
```{r, fig.width=5, fig.height=4}
heatmap_genes <- c(
  'MS4A1', 'CD40', 'IL4R', 'IL7R',
  'CD34', 'CD38', 'MME',
  'CD19')

heatmap_clusters <- data.frame(Cluster=sort(clusters[as.integer(clusters) %in% type_ids$`B cells`]))
# heatmap_clusters <- heatmap_clusters[as.integer(heatmap_clusters$Cluster) > 9, ,drop=FALSE]
PlotExpressionHeatmap(log_mtx, heatmap_clusters, heatmap_genes)
```

```{r}
b_markers_df <- data.frame(
  Type = c("Immature B cells", "Pre-pro B cells", "Pre B cells"),
  Markers = c("MS4A1 (CD20), CD40, IL4R, IL7R-", "CD34, CD38, MME (CD10), CD24-, IL7R-", "CD34-, CD40-, IL7R+, IL4R-, CD19+")
)

type_ids <- c(type_ids, lst(
  `Immature B cells` = c(3, 18),
  `Pre-pro B cells` = c(14),
  `Pre B cells` = c(11, 12)
  ))

type_ids$`B cells` <- NULL

b_markers_df$Clusters <- sapply(type_ids, paste, collapse=", ")[as.character(b_markers_df$Type)]
b_markers_df
```

```{r}
clusters_annotated <- AnnotateClusters(clusters, type_ids)
PlotClustering(pgd, clusters_annotated)
```

## T cells
```{r}
heatmap_genes <- c('CCR7', "CD3E", "CD8B", "SELL", "GNLY", "GZMA", "GZMB", "GZMH", "GZMK", "PRF1", 
                   "NKG7", "IL7R", "CD4")

heatmap_clusters <- data.frame(Cluster=sort(clusters[as.integer(clusters) %in% type_ids$`T cells`]))
PlotExpressionHeatmap(log_mtx, heatmap_clusters, heatmap_genes)
```

```{r}
t_markers_df <- data.frame(
  Type = c("Cytotoxic T cells", "T cells"),
  Markers = c("NKG7, GZMA, GZMH, GZMK", "CD3E, CD8B, IL7R")
)
```

```{r}
type_ids <- c(type_ids, lst(
  `Cytotoxic T cells` = c(7, 16, 17)
  ))

type_ids$`T cells` <- 1

clusters_annotated <- AnnotateClusters(clusters, type_ids)
PlotClustering(pgd, clusters_annotated)
```


```{r}
# Web app
# go_env <- p2.generate.human.go(pgd)
# pgd$testPathwayOverdispersion(setenv = go_env, verbose = T, correlation.distance.threshold = 0.9, 
#                               recalculate.pca = F, min.pathway.size = 100, max.pathway.size = 1000)
# 
# go_sets <- p2.generate.human.go.web(colnames(pgd$counts))
# de_sets <- get.de.geneset(pgd, groups = pgd$clusters$PCA$infomap, prefix = 'de_')
# go_sets <- c(go_sets, de_sets)
# 
# additional_metadata <- list()
# additional_metadata$altCluster <- p2.metadata.from.factor(as.factor(clusters_annotated), displayname = 'Annotated', s = 0.7, v = 0.8, start = 0, end = 0.5)
# 
# pgd_web_object <- make.p2.app(pgd, dendrogramCellGroups = pgd$clusters$PCA$infomap,
#                               additionalMetadata = additional_metadata,
#                               geneSets = go_sets,
#                               show.clusters = T)
# 
# pgd_web_object$serializeToStaticFast(binary.filename = paste0(kEstFolder, 'bmmc1_pagoda_annotated.bin'))
# saveRDS(pgd_web_object, paste0(kEstFolder, 'pagoda_annotation_web.rds'))
```

```{r}
write.csv(data.frame(Barcode=names(clusters_annotated), Type=as.vector(clusters_annotated)), paste0(kEstFolder, 'clusters_annotated.csv'))
```

